version: '3.3'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - nwp-load-test-network

  prometheus_push_gateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - nwp-load-test-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    network_mode: host

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    environment:
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - nwp-load-test-network

  nwp-load-test:
    image: nwp/nwp-load-test:latest
    volumes:
    - "./:/etc/config/nwp-load-test"
    command: ["-elasticUrl", "http://elastic:9200", "-elasticIndex", "metrics", "-scenario", "/etc/config/nwp-load-test/dev-scenario.json"]
    networks:
      - nwp-load-test-network

networks:
  nwp-load-test-network:

