version: 2
deployJobFilters: &deployJobFilters
  filters:
    branches:
      only:
      - master
      - develop
      - circle
      - /hotfix.*/
      - /release.*/
      - /docker.*/
    tags:
      only:
      - /prod-.*/

buildImage: &buildImage
  docker:
  - image: "524951270132.dkr.ecr.us-east-1.amazonaws.com/proto0:plat0-ci-build__master"
  - image: "524951270132.dkr.ecr.us-east-1.amazonaws.com/proto0:plat0-rabbitmq__latest"

deployImage: &deployImage
  docker:
  - image: "524951270132.dkr.ecr.us-east-1.amazonaws.com/proto0:plat0-ci-build__master"

componentTestImage: &componentTestImage
  docker:
  - image: "524951270132.dkr.ecr.us-east-1.amazonaws.com/proto0:plat0-ci-build__master"
  - image: "524951270132.dkr.ecr.us-east-1.amazonaws.com/proto0:plat0-rabbitmq__latest"
  - image: "524951270132.dkr.ecr.us-east-1.amazonaws.com/proto0:plat0-common-sidecar-sample__master"

aliases:
- &setupRemoteDocker
  setup_remote_docker:
    version: 17.09.0-ce
    docker_layer_caching: false
- &copySSHKey
  run:
    name: Copy SSH Key
    command: cp $HOME/.ssh/id_rsa ./docker_key
- &makeDockerSaveToWorkspace
  run:
    name: Build Docker Image using make
    command : make docker-save-to-workspace-tar
- &attachWorkspace
  attach_workspace:
    at: ~/circle_workspace
- &makeDockerLoadFromWorkspace
  run:
    name: Build Docker Image using make
    command : make docker-load-from-workspace-tar
- &pushDockerToECR
  deploy:
    name: Push image to ECR
    command: make docker-push-image-to-ecr
- &componentTest
  run:
    name: Component test
    command: make go-component-test
- &ecrLogin
  run:
    name: ECR Login
    command: make ecr-login

jobs:
  build:
    <<: *buildImage
    working_directory: "/go/src/plat0.common.sidecar.sample-go"
    steps:
    - checkout
    - *setupRemoteDocker
    - *copySSHKey
    - *makeDockerSaveToWorkspace
    - persist_to_workspace:
        root: ~/circle_workspace
        paths:
        - plat0-common-sidecar-sample.tar

  deploy-ecr:
    <<: *deployImage
    working_directory: "/go/src/plat0.common.sidecar.sample-go"
    steps:
    - checkout
    - *setupRemoteDocker
    - *attachWorkspace
    - *makeDockerLoadFromWorkspace
    - *pushDockerToECR
    - *componentTest


workflows:
  version: 2
  build:
    jobs:
    - build
    - deploy-ecr:
        #<<: *deployJobFilters
        requires:
        - build

